### ISSUE TITLE
Single feed for Swadeshi Indology Conference

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-coders/rss-feeds#1]
Especially relevant since it's not been submitted to apple etc.. yet.

**Comment by kalluparambil** [comment]
I am new to GitHub. Any pointers on how to take the issue in my name and do
status update etc? - धन्यवादः ।

**Comment by vvasuki** [comment]
It's already in your name, and you just did a "status update" by replying to this email. Just see https://github.com/sanskrit-coders/rss-feeds/issues/1#event-1303508931

**Comment by kalluparambil** [comment]
Completed. Combined both Swadeshi Indology Conference 1 and 2 into one feed: https://github.com/sanskrit-coders/rss-feeds/blob/master/feeds/en/Swadeshi-Indology-Conferences.rss
